### ISSUE TITLE
Error in peak calling with MACS2

### ISSUE THREAD

**Issue by robelTes** [GreenleafLab/ArchR#239]
Hello,
I'm not sure is it's to you that I should address this issue or to MACS2 author. However I'll submit it here and see if anyone has come across a similar situation.
While trying to do a peak calling by religiously following your tutorial, I had this error report...

```projHOS4 = addReproduciblePeakSet(ArchRProj = projHOS3)```
Searching For MACS2..
Found with $path!
ArchR logging to : ArchRLogs/ArchR-addReproduciblePeakSet-13cb76ed16b1-Date-2020-07-08_Time-17-30-42.log
If there is an issue, please report to github with logFile!
2020-07-08 17:30:44 : Peak Calling Parameters!, 0.036 mins elapsed.
   Group nCells nCellsUsed nReplicates nMin nMax maxPeaks
C1    C1    182        182           2   52  130    91000
C2    C2   1667        724           2  224  500   150000
C3    C3    558        558           2  229  329   150000
C4    C4    569        569           2  144  425   150000
C5    C5    355        355           2   40  315   150000
C6    C6    850        719           2  219  500   150000
C7    C7   1647        653           2  153  500   150000
2020-07-08 17:30:44 : Batching Peak Calls!, 0.038 mins elapsed.
2020-07-08 17:30:44 : Batch Execution w/ safelapply!, 0 mins elapsed.
Error in (function (..., threads = 1, preschedule = FALSE)  : 
Error Found Iteration 1 : 
	[1] "Error in data.table::fread(summitsFile, select = c(1, 2, 3, 5)) : \n  File '/home/rob/shares/epistress/Robel/scATAQ_HOS/archR/HOS/PeakCalls/InsertionBeds/C1._.rep2-1_summits.bed' does not exist or is non-readable. getwd()=='/home/rob/shares/epis
	<simpleError in data.table::fread(summitsFile, select = c(1, 2, 3, 5)): File '/home/rob/shares/epistress/Robel/scATAQ_HOS/archR/HOS/PeakCalls/InsertionBeds/C1._.rep2-1_summits.bed' does not exist or is non-readable. getwd()=='/home/rob/shares/epistre
Error Found Iteration 2 : 
	[1] "Error in data.table::fread(summitsFile, select = c(1, 2, 3, 5)) : \n  File '/home/rob/shares/epistress/Robel/scATAQ_HOS/archR/HOS/PeakCalls/InsertionBeds/C1._.rep1-2_summits.bed' does not exist or is non-readable. getwd()=='/home/rob/shares/epis
	<simpleError in data.table::fread(summitsFile, select = c(1, 2, 3, 5)): File '/home/rob/shares/epistress/Robel/scATAQ_HOS/archR/HOS/PeakCalls/InsertionBeds/C1._.rep1-2_summits.be
In addition: Warning message:
In mclapply(..., mc.cores = threads, mc.preschedule = preschedule) :
  14 function calls resulted in an error
[ArchR-addReproduciblePeakSet-13cb76ed16b1-Date-2020-07-08_Time-17-30-42.log](https://github.com/GreenleafLab/ArchR/files/4891769/ArchR-addReproduciblePeakSet-13cb76ed16b1-Date-2020-07-08_Time-17-30-42.log)

Went to check the InsertionBeds directory, it seems like MACS2 didn't produce the summits.bed files even though macs2 path is well found. I looked for If I can call macs2 through system2 function:
```system2("macs2","callpeak -h",wait = T)```

This one doesn't fail but the next fails

```system2("macs2","callpeak -g 2.7e+09 --name C2._.rep2-3 --treatment /home/rob/shares/epistress/Robel/scATAQ_HOS/archR/HOS/PeakCalls/InsertionBeds/C2._.rep2-3.insertions.bed --outdir /home/rob/shares/epistress/Robel/scATAQ_HOS/archR/HOS/PeakCalls/InsertionBeds --format BED --call-summits --keep-dup all -q 0.1",wait = T)```
Traceback (most recent call last):
  File "/usr/local/bin/macs2", line 4, in <module>
    __import__('pkg_resources').run_script('MACS2==2.1.3', 'macs2')
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 661, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1441, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/MACS2-2.1.3-py2.7-linux-x86_64.egg/EGG-INFO/scripts/macs2", line 622, in <module>
    main()
  File "/usr/local/lib/python2.7/dist-packages/MACS2-2.1.3-py2.7-linux-x86_64.egg/EGG-INFO/scripts/macs2", line 56, in main
    from MACS2.callpeak_cmd import run
  File "/usr/local/lib/python2.7/dist-packages/MACS2-2.1.3-py2.7-linux-x86_64.egg/MACS2/callpeak_cmd.py", line 31, in <module>
    from MACS2.OptValidator import opt_validate
  File "/usr/local/lib/python2.7/dist-packages/MACS2-2.1.3-py2.7-linux-x86_64.egg/MACS2/OptValidator.py", line 27, in <module>
    from MACS2.IO.Parser import BEDParser, ELANDResultParser, ELANDMultiParser, \
  File "MACS2/IO/Parser.pyx", line 27, in init MACS2.IO.Parser
  File "MACS2/IO/FixWidthTrack.pyx", line 30, in init MACS2.IO.FixWidthTrack
ImportError: /usr/local/lib/python2.7/dist-packages/MACS2-2.1.3-py2.7-linux-x86_64.egg/MACS2/IO/PeakIO.so: undefined symbol: PyFPE_jbuf

This seems to be due to the fact that I've multiple versions of libraries imported by MACS2 (maybe numpy ...), and some people suggested to uninstall the library and install it again. This didn't resolve the issue.
MACS2 functions well in linux terminal however, the same command ```macs2 callpeak -g 2.7e+09 --name C2._.rep2-3 --treatment /home/rob/shares/epistress/Robel/scATAQ_HOS/archR/HOS/PeakCalls/InsertionBeds/C2._.rep2-3.insertions.bed --outdir /home/rob/shares/epistress/Robel/scATAQ_HOS/archR/HOS/PeakCalls/InsertionBeds --format BED --call-summits --keep-dup all -q 0.1``` works well from terminal. 
So I launched macs2 for all the InsertionBed files that I had, but addReproduciblePeakSet overwrites the output directory every time it is launched. Do you please have a work around for this issue?

**Comment by rcorces** [comment]
Can you confirm that the path to the python executable that you are expecting to use is /usr/local/lib/python2.7?
From your log it looks like you might have python installed in a different place using miniconda or similar. Currently, ArchR is auto-detecting your MACS2 install and I have a feeling it is using a python executable that you dont have proper permissions on or that doesnt have access to the correct packages. If the auto-detected version of MACS2 is not the correct one, you can explicitly specify this using the `pathToMacs2` argument in `addReproduciblePeakSet`.

**Comment by robelTes** [comment]
```Sys.which("python2.7")```
The python executable is at /usr/bin/python2.7. 

/usr/local/lib/python2.7 is the directory containing the packages including the ones imported by MACS2.
I do have miniconda installed python packages (like numpy) somewhere else. It seems to me that when MACS2 is called via R some how it imports the packages from miniconda, but when called via terminal it imports from the right directory. That's weird

```Sys.which("macs2")```
gives the same path as what is given by ```whereis macs2```

Any who I upgraded macs2 through pip ```pip install -U MACS2``` now I got everything at /home/rob/miniconda3/bin/macs2 and gave this macs2 path to ```addReproduciblePeakSet``` and it worked!

Thank you for the quick response.

**Comment by Gavin-Lijy** [comment]
> Hello,
> I'm not sure is it's to you that I should address this issue or to MACS2 author. However I'll submit it here and see if anyone has come across a similar situation.
> While trying to do a peak calling by religiously following your tutorial, I had this error report...
> 
> `projHOS4 = addReproduciblePeakSet(ArchRProj = projHOS3)`
> Searching For MACS2..
> Found with $path!
> ArchR logging to : ArchRLogs/ArchR-addReproduciblePeakSet-13cb76ed16b1-Date-2020-07-08_Time-17-30-42.log
> If there is an issue, please report to github with logFile!
> 2020-07-08 17:30:44 : Peak Calling Parameters!, 0.036 mins elapsed.
> Group nCells nCellsUsed nReplicates nMin nMax maxPeaks
> C1 C1 182 182 2 52 130 91000
> C2 C2 1667 724 2 224 500 150000
> C3 C3 558 558 2 229 329 150000
> C4 C4 569 569 2 144 425 150000
> C5 C5 355 355 2 40 315 150000
> C6 C6 850 719 2 219 500 150000
> C7 C7 1647 653 2 153 500 150000
> 2020-07-08 17:30:44 : Batching Peak Calls!, 0.038 mins elapsed.
> 2020-07-08 17:30:44 : Batch Execution w/ safelapply!, 0 mins elapsed.
> Error in (function (..., threads = 1, preschedule = FALSE) :
> Error Found Iteration 1 :
> [1] "Error in data.table::fread(summitsFile, select = c(1, 2, 3, 5)) : \n File '/home/rob/shares/epistress/Robel/scATAQ_HOS/archR/HOS/PeakCalls/InsertionBeds/C1._.rep2-1_summits.bed' does not exist or is non-readable. getwd()=='/home/rob/shares/epis <simpleError in data.table::fread(summitsFile, select = c(1, 2, 3, 5)): File '/home/rob/shares/epistress/Robel/scATAQ_HOS/archR/HOS/PeakCalls/InsertionBeds/C1._.rep2-1_summits.bed' does not exist or is non-readable. getwd()=='/home/rob/shares/epistre
> Error Found Iteration 2 :
> [1] "Error in data.table::fread(summitsFile, select = c(1, 2, 3, 5)) : \n File '/home/rob/shares/epistress/Robel/scATAQ_HOS/archR/HOS/PeakCalls/InsertionBeds/C1._.rep1-2_summits.bed' does not exist or is non-readable. getwd()=='/home/rob/shares/epis <simpleError in data.table::fread(summitsFile, select = c(1, 2, 3, 5)): File '/home/rob/shares/epistress/Robel/scATAQ_HOS/archR/HOS/PeakCalls/InsertionBeds/C1._.rep1-2_summits.be
> In addition: Warning message:
> In mclapply(..., mc.cores = threads, mc.preschedule = preschedule) :
> 14 function calls resulted in an error
> [ArchR-addReproduciblePeakSet-13cb76ed16b1-Date-2020-07-08_Time-17-30-42.log](https://github.com/GreenleafLab/ArchR/files/4891769/ArchR-addReproduciblePeakSet-13cb76ed16b1-Date-2020-07-08_Time-17-30-42.log)
> 
> Went to check the InsertionBeds directory, it seems like MACS2 didn't produce the summits.bed files even though macs2 path is well found. I looked for If I can call macs2 through system2 function:
> `system2("macs2","callpeak -h",wait = T)`
> 
> This one doesn't fail but the next fails
> 
> `system2("macs2","callpeak -g 2.7e+09 --name C2._.rep2-3 --treatment /home/rob/shares/epistress/Robel/scATAQ_HOS/archR/HOS/PeakCalls/InsertionBeds/C2._.rep2-3.insertions.bed --outdir /home/rob/shares/epistress/Robel/scATAQ_HOS/archR/HOS/PeakCalls/InsertionBeds --format BED --call-summits --keep-dup all -q 0.1",wait = T)`
> Traceback (most recent call last):
> File "/usr/local/bin/macs2", line 4, in
> **import**('pkg_resources').run_script('MACS2==2.1.3', 'macs2')
> File "/usr/local/lib/python2.7/dist-packages/pkg_resources/**init**.py", line 661, in run_script
> self.require(requires)[0].run_script(script_name, ns)
> File "/usr/local/lib/python2.7/dist-packages/pkg_resources/**init**.py", line 1441, in run_script
> exec(code, namespace, namespace)
> File "/usr/local/lib/python2.7/dist-packages/MACS2-2.1.3-py2.7-linux-x86_64.egg/EGG-INFO/scripts/macs2", line 622, in
> main()
> File "/usr/local/lib/python2.7/dist-packages/MACS2-2.1.3-py2.7-linux-x86_64.egg/EGG-INFO/scripts/macs2", line 56, in main
> from MACS2.callpeak_cmd import run
> File "/usr/local/lib/python2.7/dist-packages/MACS2-2.1.3-py2.7-linux-x86_64.egg/MACS2/callpeak_cmd.py", line 31, in
> from MACS2.OptValidator import opt_validate
> File "/usr/local/lib/python2.7/dist-packages/MACS2-2.1.3-py2.7-linux-x86_64.egg/MACS2/OptValidator.py", line 27, in
> from MACS2.IO.Parser import BEDParser, ELANDResultParser, ELANDMultiParser,
> File "MACS2/IO/Parser.pyx", line 27, in init MACS2.IO.Parser
> File "MACS2/IO/FixWidthTrack.pyx", line 30, in init MACS2.IO.FixWidthTrack
> ImportError: /usr/local/lib/python2.7/dist-packages/MACS2-2.1.3-py2.7-linux-x86_64.egg/MACS2/IO/PeakIO.so: undefined symbol: PyFPE_jbuf
> 
> This seems to be due to the fact that I've multiple versions of libraries imported by MACS2 (maybe numpy ...), and some people suggested to uninstall the library and install it again. This didn't resolve the issue.
> MACS2 functions well in linux terminal however, the same command `macs2 callpeak -g 2.7e+09 --name C2._.rep2-3 --treatment /home/rob/shares/epistress/Robel/scATAQ_HOS/archR/HOS/PeakCalls/InsertionBeds/C2._.rep2-3.insertions.bed --outdir /home/rob/shares/epistress/Robel/scATAQ_HOS/archR/HOS/PeakCalls/InsertionBeds --format BED --call-summits --keep-dup all -q 0.1` works well from terminal.
> So I launched macs2 for all the InsertionBed files that I had, but addReproduciblePeakSet overwrites the output directory every time it is launched. Do you please have a work around for this issue?

I have exactly the same issue!

**Comment by rcorces** [comment]
This is almost certainly an issue with how MACS2 is installed. I'm not familiar with guix unfortunately.

**Comment by hanice** [comment]
I just had the same issue.
When testing this line of code (from MACS2.callpeak_cmd import run) in the python terminal,
I got the error: numpy.ndarray size changed, may indicate binary incompatibility.
So I reinstalled the numpy (pip uninstall numpy; pip install numpy), and it worked well.
Hope it helps.

**Comment by xiangrong7** [comment]
> Hello, I have the same error as robelTes of ArchR not finding the summit..bed files. When I try manually in the terminal try the command : `macs2 callpeak -g 2.7e+09 --name C2._.Rep2-4 --treatment InsertionBeds/C2._.Rep2-4.insertions.bed --outdir InsertionBeds --format BED --call-summits --keep-dup all -q 0.1 ` then it gives the error
> 
> ```
> Traceback (most recent call last):
>   File "/gnu/store/2wzsyig34dmj16wks7qdafcr82g4yy8x-macs-2.2.6/bin/.macs2-real", line 652, in <module>
>     main()
>   File "/gnu/store/2wzsyig34dmj16wks7qdafcr82g4yy8x-macs-2.2.6/bin/.macs2-real", line 51, in main
>     run( args )
>   File "/gnu/store/2wzsyig34dmj16wks7qdafcr82g4yy8x-macs-2.2.6/lib/python3.8/site-packages/MACS2/callpeak_cmd.py", line 65, in run
>     else:       (treat, control) = load_tag_files_options  (options)
>   File "/gnu/store/2wzsyig34dmj16wks7qdafcr82g4yy8x-macs-2.2.6/lib/python3.8/site-packages/MACS2/callpeak_cmd.py", line 391, in load_tag_files_options
>     treat = tp.build_fwtrack()
>   File "MACS2/IO/Parser.pyx", line 188, in MACS2.IO.Parser.GenericParser.build_fwtrack
>   File "MACS2/IO/Parser.pyx", line 203, in MACS2.IO.Parser.GenericParser.build_fwtrack
>   File "MACS2/IO/Parser.pyx", line 351, in MACS2.IO.Parser.BEDParser.__fw_parse_line
> IndexError: list index out of range
> ```
> 
> because the bed file is only 3 columns instead of 6 as MACS expects I think. Is this a just a MACS issue? I am not using conda, but guix for packaging.
> 
> This is my log file and I used the tutorial data. [ArchR-addReproduciblePeakSet-1682b5781c17-Date-2021-05-10_Time-14-27-39.log](https://github.com/GreenleafLab/ArchR/files/6457296/ArchR-addReproduciblePeakSet-1682b5781c17-Date-2021-05-10_Time-14-27-39.log)

I have the same issue. Have you solved it?

**Comment by wulc21** [comment]
I just had the same issue.
So I reinstalled the numpy (pip uninstall numpy; pip install numpy), as professor [HaniceSun](https://github.com/HaniceSun) and it worked well.

Great, than you very much ! @HaniceSun

**Comment by adler-sudo** [comment]
I was having a similar issue. 

I thought it was being caused by the bed file only containing 3 columns as @mirifax mentioned, given that the MACS2 documentation says to pass BEDPE to the --format option if passing a 3 column bed file. Therefore, I attempted to run macs2 outside of ArchR using the BEDPE option, where I was informed that one of the entries in the bed file had fewer than 3 columns. chr10 had only one entry, which contained empty values in column 1 and 2.

 After removing this row, I was able to successfully run macs2 from the command line using EITHER the BED or BEDPE options for --format.

**Comment by huyulan-funan** [comment]
> I just had the same issue. When testing this line of code (from MACS2.callpeak_cmd import run) in the python terminal, I got the error: numpy.ndarray size changed, may indicate binary incompatibility. So I reinstalled the numpy (pip uninstall numpy; pip install numpy), and it worked well. Hope it helps.

I encountered the same error, and it is sporadic. I tried to update the version of numpy (the latest version and v2.2.6) but it did not solve my problem. What version of numpy are you using? Thank you.
